include:
  - project: flywheel-io/tools/etc/qa-ci
    ref: 9175d35e0bd374113d7643af2494de58a80ed1a7
    file: ci/gears.yml

update:profiles:
  stage: update
  rules:
    - if: $UPSTREAM_PROJECT_ID && $UPSTREAM_TAG
      when: always
  script:
    - ./bin/update_profiles.sh "$UPSTREAM_TAG"
    - /ci/create_mr.sh update-profiles $CI_COMMIT_BRANCH
      title="Update classification profile to $UPSTREAM_TAG"
