include:
  - project: flywheel-io/tools/etc/qa-ci
    ref: d7b0f917c9a5e07dcc27c7787b51ec9e4f095636
    file: ci/gears.yml

update:profiles:
  stage: update
  rules:
    - if: $UPSTREAM_PROJECT_ID && $UPSTREAM_TAG
      when: always
  script:
    - sed -i "s|PROFILE_VERSION=.*|PROFILE_VERSION=$UPSTREAM_TAG|" Dockerfile
    - /ci/create_mr.sh update-profiles $CI_COMMIT_BRANCH
      title="Update classification profile to $UPSTREAM_TAG"
