[tool.poetry]
name = "fw-gear-file-classifier"
version = "0.1.0"
description = "Generic File Classifier"
authors = ["Flywheel <support@flywheel.io>"]
readme = "README.md"
license = "MIT"
keywords = [
    "Flywheel",
    "Gears",
    "Classification"
]
repository = "https://gitlab.com/flywheel-io/flywheel-apps/classifier.git"
classifiers = [
    "Topic :: Scientific/Engineering"
]

[tool.poetry.dependencies]
python = "^3.8"
flywheel-gear-toolkit = {git="https://gitlab.com/flywheel-io/public/gear-toolkit.git", rev="GEAR-1488-sdk-optional"}
fw-classification = {path = "classification-toolkit"}
fw-core-client = "^1.0.0"

[tool.poetry.dev-dependencies]
pytest = "^6.1.2"
pytest-cov = "^2.10.1"
pytest-mock = "^3.3.1"
coverage = {extras = ["toml"], version = "^5.3"}
black = "^20.8b1"
isort = "^5.6.4"
pylint = "^2.6.0"
pycodestyle = "^2.6.0"
pydocstyle = "^5.1.1"
mypy = "^0.790"
jupyter = "^1.0.0"
jupyter-client = "6.1.11"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.core.masonry.api"
